
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laundry-point
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
#logging:
#  file:
#    path: ./
#    name: dev-laundry-point.log